### ISSUE TITLE
Testing GFM task lists

### ISSUE THREAD

**Issue by mloskot** [mloskot/ci-test#1]
## Task List
- [x] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed
